=== atamurius/NC-Test-Configurator/schema.dtd
<!ELEMENT schema (group*)>

<!ELEMENT group (action+)>
<!ATTLIST group title CDATA #REQUIRED>

<!ELEMENT action (property*,result*)>
<!ATTLIST action title CDATA #REQUIRED>
<!ATTLIST action id CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property title CDATA #REQUIRED>
<!ATTLIST property type CDATA #REQUIRED>
<!-- type: enum -->
<!ATTLIST property values CDATA #IMPLIED>
<!ATTLIST property default CDATA #IMPLIED>
<!-- type: int -->
<!ATTLIST property min CDATA #IMPLIED>
<!ATTLIST property max CDATA #IMPLIED>
<!-- type: ref -->
<!ATTLIST property ref-type CDATA #IMPLIED>
<!-- type: set -->
<!ATTLIST property values CDATA #IMPLIED>
<!-- type: string -->
<!ATTLIST property max CDATA #IMPLIED>
<!ATTLIST property required CDATA #IMPLIED>
<!ATTLIST property pattern CDATA #IMPLIED>
<!-- type: bool -->

<!ELEMENT result EMPTY>
<!ATTLIST result name CDATA #REQUIRED>
<!ATTLIST result title CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>

=== atamurius/NC-Test-Configurator/schema.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scheme SYSTEM "schema.dtd">
<schema>
    <group title="Person">
        <action title="Create" id="person:create">
            <property name="firstName" title="First name" type="string" required="true"/>
            <property name="lastName" title="Last name" type="string"/>
            <property name="age" title="Age in years" type="int" min="1"/>
            <property name="gender" title="Gender" type="enum" values="Male,Female"/>
            <result name="id" title="ID" type="person:id"/>
        </action>
        <action title="Delete" id="person:delete">
            <property name="id" title="Person" type="ref" ref-type="person:id"/>
        </action>
    </group>
</schema>
