=== atamurius/NC-Test-Configurator/tests.dtd
<!ELEMENT tests (test*)>

<!ELEMENT test (scenario*)>
<!ATTLIST test title CDATA #REQUIRED>

<!ELEMENT scenario (property*)>
<!ATTLIST scenario id CDATA #REQUIRED>
<!ATTLIST scenario type CDATA #REQUIRED>
<!ATTLIST scenario title CDATA #REQUIRED>

<!ELEMENT property (item*)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>

<!ELEMENT item EMPTY>
<!ATTLIST item key CDATA #IMPLIED>
<!ATTLIST item value CDATA #IMPLIED>

=== atamurius/NC-Test-Configurator/test3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tests SYSTEM "tests.dtd">
<tests>
  <test title="New test">
    <scenario id="scenario0" title="Example scenario" type="com.netcracker.tc.tests.examples.Types.scenario">
      <property name="bool" value="true"/>
      <property name="enumeration" value="DEFAULT"/>
      <property name="list">
        <item value="first"/>
        <item value="second"/>
        <item value="last"/>
      </property>
      <property name="map">
        <item key="key1" value="value1"/>
        <item key="key2" value="value2"/>
      </property>
      <property name="integer" value="42"/>
      <property name="real" value="0.12"/>
      <property name="date" value="31/12/2012"/>
    </scenario>
  </test>
</tests>

=== atamurius/NC-Test-Configurator/test1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tests SYSTEM "tests.dtd">
<tests>
  <test title="Create and remove">
    <scenario id="scenario0" title="Create" type="person:create">
      <property name="firstName" value="Alex"/>
      <property name="lastName" value="Estporsky"/>
      <property name="age" value="21"/>
      <property name="gender" value="Male"/>
    </scenario>
    <scenario id="scenario1" title="Delete" type="person:delete">
      <property name="id" value="scenario0.id"/>
    </scenario>
  </test>
  <test title="Create female">
    <scenario id="scenario0" title="Create" type="person:create">
      <property name="firstName" value="Mary"/>
      <property name="lastName" value="Jhonson"/>
      <property name="age" value="31"/>
      <property name="gender" value="Female"/>
    </scenario>
  </test>
</tests>

=== atamurius/NC-Test-Configurator/test2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tests SYSTEM "tests.dtd">
<tests>
  <test title="Persons">
    <scenario id="scenario0" title="Generate random persons" type="com.netcracker.tc.tests.examples.Person.generateRandomPersons"/>
    <scenario id="scenario1" title="Create" type="com.netcracker.tc.tests.examples.Person.create">
      <property name="firstName" value="Aleksej"/>
      <property name="lastName" value="Doe"/>
      <property name="age" value="21"/>
      <property name="gender" value="MALE"/>
    </scenario>
    <scenario id="scenario2" title="Delete" type="com.netcracker.tc.tests.examples.Person.delete">
      <property name="person" value="scenario0.secondPerson"/>
    </scenario>
  </test>
  <test title="Switchs">
    <scenario id="scenario0" title="Create" type="com.netcracker.tc.tests.examples.Switch.create">
      <property name="name" value=""/>
      <property name="portCount" value="10"/>
    </scenario>
    <scenario id="scenario1" title="Delete port" type="com.netcracker.tc.tests.examples.Switch.deletePort">
      <property name="switch" value="scenario0.returnValue"/>
      <property name="portId" value="3"/>
      <property name="deadPort" value="true"/>
    </scenario>
    <scenario id="scenario2" title="Delete switch" type="com.netcracker.tc.tests.examples.Switch.deleteSwitch">
      <property name="switch" value="scenario0.returnValue"/>
    </scenario>
  </test>
</tests>

=== atamurius/NC-Test-Configurator/tests.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tests SYSTEM "tests.dtd">
<tests>
  <test title="New test">
    <scenario id="scenario0" title="Example scenario" type="com.netcracker.tconf.examples.Types.scenario">
      <property name="arg#0" value="0"/>
      <property name="arg#1.bool" value="true"/>
      <property name="arg#1.enumeration" value="DEFAULT"/>
      <property name="arg#1.optionalEnum" value=""/>
      <property name="arg#1.list">
        <item value="first"/>
        <item value="second"/>
        <item value="third"/>
      </property>
      <property name="arg#1.map">
        <item key="key3" value="value3"/>
        <item key="key2" value="value2"/>
        <item key="key1" value="value1"/>
      </property>
      <property name="arg#1.integer" value="42"/>
      <property name="arg#1.real" value="0.0"/>
      <property name="arg#1.date" value="12/03/2012"/>
      <property name="arg#1.optionalString" value=""/>
      <property name="arg#1.optionalXML_Reference" value=""/>
      <property name="arg#2" value="0"/>
      <property name="arg#3.someXML_string" value="&lt;?xml version=&quot;1.0&quot;?&gt;"/>
    </scenario>
  </test>
</tests>
